In [1]:
import pandas as pd
new = pd.read_csv('2007-2008_School_Progress_Report.csv')
old = pd.read_csv('clean_data.csv')

In [3]:
new.tail(15)

,DBN,DISTRICT,SCHOOL,PRINCIPAL,2007-08 SCHOOL SUPPORT ORGANIZATION,PROGRESS REPORT TYPE,SCHOOL LEVEL*,PEER INDEX*,OVERALL GRADE,OVERALL SCORE,ENVIRONMENT CATEGORY SCORE,ENVIRONMENT GRADE,PERFORMANCE CATEGORY SCORE,PERFORMANCE GRADE,PROGRESS CATEGORY SCORE,PROGRESS GRADE,ADDITIONAL CREDIT,2006-07 PROGRESS REPORT GRADE,2007-08 QUALITY REVIEW SCORE,2006-07 FEDERAL ACCOUNTABILITY STATUS
1478,84Q706,84,OUR WORLD NEIGHBORHOOD CHARTER,Brian Ferguson,Charter,ESMS,K-8,21.40,B,62.6,9.4,B,11.3,C,35.9,B,6.00,NaN,NaN,In Good Standing
1479,84X165,84,GRAND CONCOURSE CHARTER SCHOOL,Ira Victor,Charter,ESMS,Elementary School,53.59,B,55.1,12.2,A,21.9,A,21.0,C,0.00,NaN,NaN,In Good Standing
1480,84X185,84,THE BRONX LIGHTHOUSE CHARTER SCHOOL,Jeffrey Tsang,Charter,ESMS,Elementary School,51.66,A,87.4,11.2,A,16.1,A,55.6,A,4.50,C,NaN,In Good Standing
1481,84X255,84,BRONX CHARTER SCHOOL FOR EXCELLENCE,Charlene Reid,Charter,ESMS,Elementary School,47.24,A,96.5,11.5,A,25.0,A,60.0,A,0.00,NaN,NaN,In Good Standing
1482,84X345,84,HYDE LEADERSHIP CHARTER SCHOOL,Joanne Goubourn,Charter,ESMS,K-8,55.17,B,65.2,13.0,A,12.6,C,37.3,A,2.25,NaN,NaN,NaN
1483,84X347,84,INTERNATIONAL LEADERSHIP CHARTER SCHOOL,Elaine Ruiz Lopez,Charter,HS,High School,2.29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,In Good Standing
1484,84X407,84,BRONX CHARTER SCHOOL FOR CHILDREN,Karen Drezner,Charter,ESMS,Elementary School,43.91,C,43.4,7.0,B,9.9,C,25.7,B,0.75,NaN,NaN,In Good Standing
1485,84X703,84,BRONX PREP CHARTER SCHOOL,Kristen Keams-Jordan,Charter,ESMS,Middle School,3.27,B,63.4,13.2,A,18.0,A,29.9,B,2.25,NaN,NaN,In Good Standing
1486,84X703,84,BRONX PREP CHARTER SCHOOL,Samona Tait,Charter,HS,High School,2.84,B,51.1,11.1,A,9.8,C,30.2,B,0.00,NaN,NaN,In Good Standing
1487,84X704,84,KIPP ACADEMY CHARTER SCHOOL,Quinton Vance,Charter,ESMS,Middle School,3.37,B,64.7,15.0,A,22.1,A,24.6,C,3.00,A,NaN,In Good Standing
1488,84X705,84,FAMILY LIFE ACADEMY CHARTER SCHOOL,Marilyn Calo,Charter,ESMS,Elementary School,58.94,A,68.9,14.8,A,19.9,A,34.2,A,0.00,NaN,NaN,NaN
1489,84X706,84,HARRIET TUBMAN CHARTER SCHOOL,Gwen Stephens,Charter,ESMS,K-8,52.56,D,36.1,2.3,D,10.3,C,23.5,C,0.00,NaN,NaN,In Good Standing
1490,84X717,84,CARL C. ICAHN CHARTER SCHOOL,Jeffrey Litt,Charter,ESMS,K-8,51.69,B,57.9,10.4,B,23.2,A,24.3,C,0.00,NaN,NaN,In Good Standing
1491,84X718,84,BRONX CHARTER SCHOOL FOR BETTER LEARNING,Ted Swartz,Charter,ESMS,Elementary School,43.51,B,54.0,11.6,A,13.9,B,28.5,B,0.00,NaN,NaN,In Good Standing
1492,84X730,84,BRONX CHARTER SCHOOL FOR ARTS,Xanthe Jory,Charter,ESMS,Elementary School,58.35,B,56.7,8.1,B,13.0,B,34.8,A,0.75,NaN,NaN,In Good Standing

In [3]:
old.head(16)

,Unnamed: 0,SCHOOL,SCHOOL LEVEL*,PEER INDEX*,GRADE,OVERALL SCORE,ENVIRONMENT CATEGORY SCORE,PERFORMANCE CATEGORY SCORE,PROGRESS CATEGORY SCORE,ADDITIONAL CREDIT,QUALITY REVIEW SCORE,Enrollment,Student-Teacher Ratio,Free-Reduced Lunch
0,0,BARD HIGH SCHOOL EARLY COLLEGE,High School,3.77,B,57.80,0.715,0.607,0.524,0.00,Well-Developed,589,17.3,43.5
1,1,CHILDREN'S WORKSHOP SCHOOL,Elementary School,39.10,B,56.81,0.508,0.462,0.615,1.50,Proficient,318,16.7,45.3
2,2,EARTH SCHOOL,Elementary School,41.67,B,55.18,0.985,0.446,0.492,0.00,Well-Developed,349,12.0,52.4
3,3,EAST SIDE COMMUNITY HIGH SCHOOL,High School,2.66,A,71.33,0.788,0.640,0.624,6.00,Well-Developed,678,13.8,65.3
4,4,MARTA VALLE SECONDARY SCHOOL,High School,2.63,C,36.00,0.250,0.387,0.375,0.00,Undeveloped,149,12.4,93.3
5,5,MARTA VALLE SECONDARY SCHOOL,Middle School,2.89,D,34.90,0.297,0.513,0.274,0.00,Undeveloped,303,13.7,43.9
6,6,NEIGHBORHOOD SCHOOL,Elementary School,37.76,B,53.08,0.821,0.429,0.507,0.00,Proficient,1729,18.7,23.5
7,7,"NEW EXPLORATIONS INTO SCIENCE, TECHNOLOGY AND ...",High School,3.62,A,84.74,0.611,1.021,0.817,0.00,Undeveloped,201,11.1,82.6
8,8,PS 015 ROBERTO CLEMENTE,Elementary School,75.60,B,52.31,0.278,0.231,0.694,3.00,Undeveloped,379,14.5,61.5
9,9,PS 019 ASHER LEVY,Elementary School,59.25,B,51.24,0.510,0.466,0.511,1.50,Proficient,293,9.1,91.1
10,10,PS 020 ANNA SILVER,Elementary School,69.78,B,52.59,0.568,0.682,0.402,1.50,Well-Developed,371,11.9,87.6
11,11,PS 034 FRANKLIN D ROOSEVELT,K-8 School,71.90,C,47.02,0.409,0.366,0.530,0.75,Proficient,344,9.8,97.4
12,12,PS 063 WILLIAM MCKINLEY,Elementary School,62.17,C,44.66,0.199,0.511,0.479,0.00,Proficient,191,9.5,84.8
13,13,PS 064 ROBERT SIMON,Elementary School,71.90,C,48.43,0.561,0.586,0.408,0.00,Well-Developed,682,13.3,67.9
14,14,PS 110 FLORENCE NIGHTINGALE,Elementary School,54.96,B,51.17,0.818,0.644,0.315,2.25,Proficient,431,11.6,91.6
15,15,PS 134 HENRIETTA SZOLD,Elementary School,66.49,B,54.21,0.338,0.550,0.566,1.50,Well-Developed,258,7.1,76.7

In [4]:
ONE = new[new['SCHOOL']=='BARD HIGH SCHOOL EARLY COLLEGE']
TWO = new[new['SCHOOL']=='P.S. 140 NATHAN STRAUS']
THREE = new[new['SCHOOL']=='EARTH SCHOOL']
FOUR = new[new['SCHOOL']=='EAST SIDE COMMUNITY HIGH SCHOOL']
FIVE = new[new['SCHOOL']=='MARTA VALLE SECONDARY SCHOOL']
SIX = new[new['SCHOOL']=='MARTA VALLE SECONDARY SCHOOL']
SEVEN = new[new['SCHOOL']=='NEIGHBORHOOD SCHOOL']
EIGHT = new[new['SCHOOL']=='P.S. 015 ROBERTO CLEMENTE']
NINE = new[new['SCHOOL']=='P.S. 019 ASHER LEVY']
TEN = new[new['SCHOOL']=='P.S. 020 ANNA SILVER']
ELEVEN = new[new['SCHOOL']=='P.S. 034 FRANKLIN D. ROOSEVELT']
TWELVE = new[new['SCHOOL']=='P.S. 063 WILLIAM MCKINLEY']
THRITEEN = new[new['SCHOOL']=='P.S. 064 ROBERT SIMON']
FOURTEEN = new[new['SCHOOL']=='P.S. 110 FLORENCE NIGHTINGALE']
FIFTEEN = new[new['SCHOOL']=='P.S. 134 HENRIETTA SZOLD']

In [5]:
new_new = pd.concat([ONE, TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE, TEN, 
                     ELEVEN, TWELVE, THRITEEN, FOURTEEN, FIFTEEN], ignore_index=True)

In [6]:
new_new

,DBN,DISTRICT,SCHOOL,PRINCIPAL,2007-08 SCHOOL SUPPORT ORGANIZATION,PROGRESS REPORT TYPE,SCHOOL LEVEL*,PEER INDEX*,OVERALL GRADE,OVERALL SCORE,ENVIRONMENT CATEGORY SCORE,ENVIRONMENT GRADE,PERFORMANCE CATEGORY SCORE,PERFORMANCE GRADE,PROGRESS CATEGORY SCORE,PROGRESS GRADE,ADDITIONAL CREDIT,2006-07 PROGRESS REPORT GRADE,2007-08 QUALITY REVIEW SCORE,2006-07 FEDERAL ACCOUNTABILITY STATUS
0,01M696,1,BARD HIGH SCHOOL EARLY COLLEGE,Raymond Peterson,ESO,HS,High School,3.79,B,57.8,10.9,A,15.9,B,31.0,B,0.00,B,Proficient,In Good Standing
1,01M140,1,P.S. 140 NATHAN STRAUS,Esteban Barrientos,ESO,ESMS,K-8,62.46,B,64.8,9.0,B,15.3,B,36.0,B,4.50,B,Proficient,In Need of Improvement - Year 1
2,01M364,1,EARTH SCHOOL,Alison Gail Hazut,ESO,ESMS,Elementary School,34.68,A,62.4,11.9,A,9.8,C,36.9,A,3.75,B,Well Developed,In Good Standing
3,01M450,1,EAST SIDE COMMUNITY HIGH SCHOOL,Mark Federman,ESO,ESMS,Middle School,2.99,A,76.5,8.8,B,19.6,A,42.8,A,5.25,A,Well Developed,In Good Standing
4,01M450,1,EAST SIDE COMMUNITY HIGH SCHOOL,Mark Federman,ESO,HS,High School,2.27,A,68.3,13.0,A,19.9,A,33.4,B,2.00,A,Well Developed,In Good Standing
5,01M509,1,MARTA VALLE SECONDARY SCHOOL,Jayne Godlewski,ICI,ESMS,Middle School,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.50,D,Proficient,Restructuring - Year 4
6,01M509,1,MARTA VALLE SECONDARY SCHOOL,Jayne Godlewski,ICI,HS,High School,2.08,B,52.6,5.3,C,8.8,C,35.5,A,3.00,C,Proficient,Restructuring - Year 4
7,01M509,1,MARTA VALLE SECONDARY SCHOOL,Jayne Godlewski,ICI,ESMS,Middle School,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.50,D,Proficient,Restructuring - Year 4
8,01M509,1,MARTA VALLE SECONDARY SCHOOL,Jayne Godlewski,ICI,HS,High School,2.08,B,52.6,5.3,C,8.8,C,35.5,A,3.00,C,Proficient,Restructuring - Year 4
9,01M363,1,NEIGHBORHOOD SCHOOL,Judith Foster,ESO,ESMS,Elementary School,33.34,D,32.1,12.2,A,9.6,C,9.5,F,0.75,B,Well Developed,In Good Standing
10,01M015,1,P.S. 015 ROBERTO CLEMENTE,Thomas Staebell,ICI,ESMS,Elementary School,63.28,D,31.9,5.8,C,8.0,C,18.1,C,0.00,B,Proficient,In Good Standing
11,01M019,1,P.S. 019 ASHER LEVY,Ivan Kushner,ESO,ESMS,Elementary School,50.39,B,50.8,9.0,B,11.4,B,30.4,B,0.00,B,Well Developed,In Good Standing
12,01M020,1,P.S. 020 ANNA SILVER,Felix Gil,ICI,ESMS,Elementary School,57.37,A,69.7,9.7,A,20.0,A,37.7,A,2.25,B,Well Developed,In Need of Improvement - Year 2
13,01M034,1,P.S. 034 FRANKLIN D. ROOSEVELT,Joyce Stallings Harte,ICI,ESMS,K-8,58.96,B,59.8,4.5,D,10.6,C,37.9,A,6.75,C,Well Developed,In Good Standing
14,01M063,1,P.S. 063 WILLIAM MCKINLEY,Darlene Despeignes,ICI,ESMS,Elementary School,53.00,F,26.5,7.6,B,11.3,C,7.6,F,0.00,C,Proficient,In Good Standing
15,01M064,1,P.S. 064 ROBERT SIMON,Sandra Litrico Pappas,ESO,ESMS,Elementary School,60.63,A,79.7,12.1,A,18.9,A,46.4,A,2.25,C,Well Developed,In Good Standing
16,01M110,1,P.S. 110 FLORENCE NIGHTINGALE,Irene Quvus,ESO,ESMS,Elementary School,42.56,C,41.2,9.4,A,16.9,A,13.4,D,1.50,B,Well Developed,In Good Standing
17,01M134,1,P.S. 134 HENRIETTA SZOLD,Loretta Caputo,ICI,ESMS,Elementary School,54.03,B,53.0,5.8,C,14.4,B,31.3,B,1.50,B,Proficient,In Good Standing

In [7]:
new_new.drop(index=[5,7], inplace=True)

In [8]:
new_new.reset_index(inplace=True)

In [9]:
new_new

,index,DBN,DISTRICT,SCHOOL,PRINCIPAL,2007-08 SCHOOL SUPPORT ORGANIZATION,PROGRESS REPORT TYPE,SCHOOL LEVEL*,PEER INDEX*,OVERALL GRADE,...,ENVIRONMENT CATEGORY SCORE,ENVIRONMENT GRADE,PERFORMANCE CATEGORY SCORE,PERFORMANCE GRADE,PROGRESS CATEGORY SCORE,PROGRESS GRADE,ADDITIONAL CREDIT,2006-07 PROGRESS REPORT GRADE,2007-08 QUALITY REVIEW SCORE,2006-07 FEDERAL ACCOUNTABILITY STATUS
0,0,01M696,1,BARD HIGH SCHOOL EARLY COLLEGE,Raymond Peterson,ESO,HS,High School,3.79,B,...,10.9,A,15.9,B,31.0,B,0.00,B,Proficient,In Good Standing
1,1,01M140,1,P.S. 140 NATHAN STRAUS,Esteban Barrientos,ESO,ESMS,K-8,62.46,B,...,9.0,B,15.3,B,36.0,B,4.50,B,Proficient,In Need of Improvement - Year 1
2,2,01M364,1,EARTH SCHOOL,Alison Gail Hazut,ESO,ESMS,Elementary School,34.68,A,...,11.9,A,9.8,C,36.9,A,3.75,B,Well Developed,In Good Standing
3,3,01M450,1,EAST SIDE COMMUNITY HIGH SCHOOL,Mark Federman,ESO,ESMS,Middle School,2.99,A,...,8.8,B,19.6,A,42.8,A,5.25,A,Well Developed,In Good Standing
4,4,01M450,1,EAST SIDE COMMUNITY HIGH SCHOOL,Mark Federman,ESO,HS,High School,2.27,A,...,13.0,A,19.9,A,33.4,B,2.00,A,Well Developed,In Good Standing
5,6,01M509,1,MARTA VALLE SECONDARY SCHOOL,Jayne Godlewski,ICI,HS,High School,2.08,B,...,5.3,C,8.8,C,35.5,A,3.00,C,Proficient,Restructuring - Year 4
6,8,01M509,1,MARTA VALLE SECONDARY SCHOOL,Jayne Godlewski,ICI,HS,High School,2.08,B,...,5.3,C,8.8,C,35.5,A,3.00,C,Proficient,Restructuring - Year 4
7,9,01M363,1,NEIGHBORHOOD SCHOOL,Judith Foster,ESO,ESMS,Elementary School,33.34,D,...,12.2,A,9.6,C,9.5,F,0.75,B,Well Developed,In Good Standing
8,10,01M015,1,P.S. 015 ROBERTO CLEMENTE,Thomas Staebell,ICI,ESMS,Elementary School,63.28,D,...,5.8,C,8.0,C,18.1,C,0.00,B,Proficient,In Good Standing
9,11,01M019,1,P.S. 019 ASHER LEVY,Ivan Kushner,ESO,ESMS,Elementary School,50.39,B,...,9.0,B,11.4,B,30.4,B,0.00,B,Well Developed,In Good Standing
10,12,01M020,1,P.S. 020 ANNA SILVER,Felix Gil,ICI,ESMS,Elementary School,57.37,A,...,9.7,A,20.0,A,37.7,A,2.25,B,Well Developed,In Need of Improvement - Year 2
11,13,01M034,1,P.S. 034 FRANKLIN D. ROOSEVELT,Joyce Stallings Harte,ICI,ESMS,K-8,58.96,B,...,4.5,D,10.6,C,37.9,A,6.75,C,Well Developed,In Good Standing
12,14,01M063,1,P.S. 063 WILLIAM MCKINLEY,Darlene Despeignes,ICI,ESMS,Elementary School,53.00,F,...,7.6,B,11.3,C,7.6,F,0.00,C,Proficient,In Good Standing
13,15,01M064,1,P.S. 064 ROBERT SIMON,Sandra Litrico Pappas,ESO,ESMS,Elementary School,60.63,A,...,12.1,A,18.9,A,46.4,A,2.25,C,Well Developed,In Good Standing
14,16,01M110,1,P.S. 110 FLORENCE NIGHTINGALE,Irene Quvus,ESO,ESMS,Elementary School,42.56,C,...,9.4,A,16.9,A,13.4,D,1.50,B,Well Developed,In Good Standing
15,17,01M134,1,P.S. 134 HENRIETTA SZOLD,Loretta Caputo,ICI,ESMS,Elementary School,54.03,B,...,5.8,C,14.4,B,31.3,B,1.50,B,Proficient,In Good Standing

In [10]:
# I want to be able to check my model to see if it's try that it would give me an accurate reading using the
# new-new data set -- need to get enrollment data... choose top five and get the info to add

In [11]:
new_new.columns

Index(['index', 'DBN', 'DISTRICT', 'SCHOOL', 'PRINCIPAL',
       '2007-08 SCHOOL SUPPORT ORGANIZATION', 'PROGRESS REPORT TYPE',
       'SCHOOL LEVEL*', 'PEER INDEX*', 'OVERALL GRADE', 'OVERALL SCORE',
       'ENVIRONMENT CATEGORY SCORE', 'ENVIRONMENT GRADE',
       'PERFORMANCE CATEGORY SCORE', 'PERFORMANCE GRADE',
       'PROGRESS CATEGORY SCORE', 'PROGRESS GRADE', 'ADDITIONAL CREDIT',
       '2006-07 PROGRESS REPORT GRADE', '2007-08 QUALITY REVIEW SCORE',
       '2006-07 FEDERAL ACCOUNTABILITY STATUS'],
      dtype='object')

In [12]:
new_new.drop(['index', 'DBN', 'DISTRICT', 'PRINCIPAL', '2007-08 SCHOOL SUPPORT ORGANIZATION',
             'PROGRESS REPORT TYPE', 'ENVIRONMENT GRADE', 'PERFORMANCE GRADE', 'PROGRESS GRADE',
             '2006-07 PROGRESS REPORT GRADE', '2006-07 FEDERAL ACCOUNTABILITY STATUS'], axis= 1, inplace=True)

In [13]:
new_new.drop(index=3, inplace=True)

In [14]:
new_new.drop(index=5, inplace=True)

In [15]:
new_new

,SCHOOL,SCHOOL LEVEL*,PEER INDEX*,OVERALL GRADE,OVERALL SCORE,ENVIRONMENT CATEGORY SCORE,PERFORMANCE CATEGORY SCORE,PROGRESS CATEGORY SCORE,ADDITIONAL CREDIT,2007-08 QUALITY REVIEW SCORE
0,BARD HIGH SCHOOL EARLY COLLEGE,High School,3.79,B,57.8,10.9,15.9,31.0,0.00,Proficient
1,P.S. 140 NATHAN STRAUS,K-8,62.46,B,64.8,9.0,15.3,36.0,4.50,Proficient
2,EARTH SCHOOL,Elementary School,34.68,A,62.4,11.9,9.8,36.9,3.75,Well Developed
4,EAST SIDE COMMUNITY HIGH SCHOOL,High School,2.27,A,68.3,13.0,19.9,33.4,2.00,Well Developed
6,MARTA VALLE SECONDARY SCHOOL,High School,2.08,B,52.6,5.3,8.8,35.5,3.00,Proficient
7,NEIGHBORHOOD SCHOOL,Elementary School,33.34,D,32.1,12.2,9.6,9.5,0.75,Well Developed
8,P.S. 015 ROBERTO CLEMENTE,Elementary School,63.28,D,31.9,5.8,8.0,18.1,0.00,Proficient
9,P.S. 019 ASHER LEVY,Elementary School,50.39,B,50.8,9.0,11.4,30.4,0.00,Well Developed
10,P.S. 020 ANNA SILVER,Elementary School,57.37,A,69.7,9.7,20.0,37.7,2.25,Well Developed
11,P.S. 034 FRANKLIN D. ROOSEVELT,K-8,58.96,B,59.8,4.5,10.6,37.9,6.75,Well Developed
12,P.S. 063 WILLIAM MCKINLEY,Elementary School,53.00,F,26.5,7.6,11.3,7.6,0.00,Proficient
13,P.S. 064 ROBERT SIMON,Elementary School,60.63,A,79.7,12.1,18.9,46.4,2.25,Well Developed
14,P.S. 110 FLORENCE NIGHTINGALE,Elementary School,42.56,C,41.2,9.4,16.9,13.4,1.50,Well Developed
15,P.S. 134 HENRIETTA SZOLD,Elementary School,54.03,B,53.0,5.8,14.4,31.3,1.50,Proficient

In [16]:
# bard enrollment: 614 student ratio: 4.9         lunch: 44
# 140 Nathan: 318      student ratio: 9.2         lunch: 72
# Earth: 344           student ratio: 7.3         lunch: 48
# East Side HS: 675    student ratio: 6.4         lunch: 67
# Marta: 95            student ratio: 15.8         lunch: 90
# Neighor: 310         student ratio: 7.1         lunch: 39
# Roberto: 190         student ratio: 11.0         lunch: 83
# Asher: 241           student ratio: 15.4          lunch: 75
# Anna: 476            student ratio: 7.7         lunch: 56
# Franklin: 293        student ratio: 13.7         lunch: 98
# William: 1859        student ratio: 4.7         lunch: 73
# Robert: 236          student ratio: 11.9         lunch: 95
# Florence: 396        student ratio: 7.0         lunch: 56
# Henrietta: 254       student ratio: 14.9         lunch: 89

In [17]:
new_new['Enrollment'] = [614, 318, 344, 675, 95, 310, 190, 241, 476, 293, 1859, 236, 396, 254]
new_new['Student-Teacher Ratio'] = [4.9, 9.2, 7.3, 6.4, 15.8, 7.1, 11.0, 15.4, 7.7, 13.7, 4.7, 11.9, 7.0, 14.9]
new_new['Free-Reduced Lunch'] = [44, 72, 48, 67, 90, 39, 83, 75, 56, 98, 73, 95, 56, 89]

In [18]:
new_new

,SCHOOL,SCHOOL LEVEL*,PEER INDEX*,OVERALL GRADE,OVERALL SCORE,ENVIRONMENT CATEGORY SCORE,PERFORMANCE CATEGORY SCORE,PROGRESS CATEGORY SCORE,ADDITIONAL CREDIT,2007-08 QUALITY REVIEW SCORE,Enrollment,Student-Teacher Ratio,Free-Reduced Lunch
0,BARD HIGH SCHOOL EARLY COLLEGE,High School,3.79,B,57.8,10.9,15.9,31.0,0.00,Proficient,614,4.9,44
1,P.S. 140 NATHAN STRAUS,K-8,62.46,B,64.8,9.0,15.3,36.0,4.50,Proficient,318,9.2,72
2,EARTH SCHOOL,Elementary School,34.68,A,62.4,11.9,9.8,36.9,3.75,Well Developed,344,7.3,48
4,EAST SIDE COMMUNITY HIGH SCHOOL,High School,2.27,A,68.3,13.0,19.9,33.4,2.00,Well Developed,675,6.4,67
6,MARTA VALLE SECONDARY SCHOOL,High School,2.08,B,52.6,5.3,8.8,35.5,3.00,Proficient,95,15.8,90
7,NEIGHBORHOOD SCHOOL,Elementary School,33.34,D,32.1,12.2,9.6,9.5,0.75,Well Developed,310,7.1,39
8,P.S. 015 ROBERTO CLEMENTE,Elementary School,63.28,D,31.9,5.8,8.0,18.1,0.00,Proficient,190,11.0,83
9,P.S. 019 ASHER LEVY,Elementary School,50.39,B,50.8,9.0,11.4,30.4,0.00,Well Developed,241,15.4,75
10,P.S. 020 ANNA SILVER,Elementary School,57.37,A,69.7,9.7,20.0,37.7,2.25,Well Developed,476,7.7,56
11,P.S. 034 FRANKLIN D. ROOSEVELT,K-8,58.96,B,59.8,4.5,10.6,37.9,6.75,Well Developed,293,13.7,98
12,P.S. 063 WILLIAM MCKINLEY,Elementary School,53.00,F,26.5,7.6,11.3,7.6,0.00,Proficient,1859,4.7,73
13,P.S. 064 ROBERT SIMON,Elementary School,60.63,A,79.7,12.1,18.9,46.4,2.25,Well Developed,236,11.9,95
14,P.S. 110 FLORENCE NIGHTINGALE,Elementary School,42.56,C,41.2,9.4,16.9,13.4,1.50,Well Developed,396,7.0,56
15,P.S. 134 HENRIETTA SZOLD,Elementary School,54.03,B,53.0,5.8,14.4,31.3,1.50,Proficient,254,14.9,89

In [19]:
new_new.rename(columns = {'PEER INDEX*': 'PEER INDEX'}, inplace=True)
new_new.rename(columns = {'SCHOOL LEVEL*': 'SCHOOL LEVEL'}, inplace=True)

In [20]:
new_new

,SCHOOL,SCHOOL LEVEL,PEER INDEX,OVERALL GRADE,OVERALL SCORE,ENVIRONMENT CATEGORY SCORE,PERFORMANCE CATEGORY SCORE,PROGRESS CATEGORY SCORE,ADDITIONAL CREDIT,2007-08 QUALITY REVIEW SCORE,Enrollment,Student-Teacher Ratio,Free-Reduced Lunch
0,BARD HIGH SCHOOL EARLY COLLEGE,High School,3.79,B,57.8,10.9,15.9,31.0,0.00,Proficient,614,4.9,44
1,P.S. 140 NATHAN STRAUS,K-8,62.46,B,64.8,9.0,15.3,36.0,4.50,Proficient,318,9.2,72
2,EARTH SCHOOL,Elementary School,34.68,A,62.4,11.9,9.8,36.9,3.75,Well Developed,344,7.3,48
4,EAST SIDE COMMUNITY HIGH SCHOOL,High School,2.27,A,68.3,13.0,19.9,33.4,2.00,Well Developed,675,6.4,67
6,MARTA VALLE SECONDARY SCHOOL,High School,2.08,B,52.6,5.3,8.8,35.5,3.00,Proficient,95,15.8,90
7,NEIGHBORHOOD SCHOOL,Elementary School,33.34,D,32.1,12.2,9.6,9.5,0.75,Well Developed,310,7.1,39
8,P.S. 015 ROBERTO CLEMENTE,Elementary School,63.28,D,31.9,5.8,8.0,18.1,0.00,Proficient,190,11.0,83
9,P.S. 019 ASHER LEVY,Elementary School,50.39,B,50.8,9.0,11.4,30.4,0.00,Well Developed,241,15.4,75
10,P.S. 020 ANNA SILVER,Elementary School,57.37,A,69.7,9.7,20.0,37.7,2.25,Well Developed,476,7.7,56
11,P.S. 034 FRANKLIN D. ROOSEVELT,K-8,58.96,B,59.8,4.5,10.6,37.9,6.75,Well Developed,293,13.7,98
12,P.S. 063 WILLIAM MCKINLEY,Elementary School,53.00,F,26.5,7.6,11.3,7.6,0.00,Proficient,1859,4.7,73
13,P.S. 064 ROBERT SIMON,Elementary School,60.63,A,79.7,12.1,18.9,46.4,2.25,Well Developed,236,11.9,95
14,P.S. 110 FLORENCE NIGHTINGALE,Elementary School,42.56,C,41.2,9.4,16.9,13.4,1.50,Well Developed,396,7.0,56
15,P.S. 134 HENRIETTA SZOLD,Elementary School,54.03,B,53.0,5.8,14.4,31.3,1.50,Proficient,254,14.9,89

In [21]:
new_new['SCHOOL LEVEL'] = new_new['SCHOOL LEVEL'].map({'Elementary School': 0, 'K-8': 1, 'High School': 3})
new_new['OVERALL GRADE'] = new_new['OVERALL GRADE'].map({'A': 0, 'B': 1, 'C': 2, 'D': 3, 'F': 4})
new_new['2007-08 QUALITY REVIEW SCORE'] = new_new['2007-08 QUALITY REVIEW SCORE'].map({'Well Developed': 1, 'Proficient': 2})

In [22]:
new_new

,SCHOOL,SCHOOL LEVEL,PEER INDEX,OVERALL GRADE,OVERALL SCORE,ENVIRONMENT CATEGORY SCORE,PERFORMANCE CATEGORY SCORE,PROGRESS CATEGORY SCORE,ADDITIONAL CREDIT,2007-08 QUALITY REVIEW SCORE,Enrollment,Student-Teacher Ratio,Free-Reduced Lunch
0,BARD HIGH SCHOOL EARLY COLLEGE,3,3.79,1,57.8,10.9,15.9,31.0,0.00,2,614,4.9,44
1,P.S. 140 NATHAN STRAUS,1,62.46,1,64.8,9.0,15.3,36.0,4.50,2,318,9.2,72
2,EARTH SCHOOL,0,34.68,0,62.4,11.9,9.8,36.9,3.75,1,344,7.3,48
4,EAST SIDE COMMUNITY HIGH SCHOOL,3,2.27,0,68.3,13.0,19.9,33.4,2.00,1,675,6.4,67
6,MARTA VALLE SECONDARY SCHOOL,3,2.08,1,52.6,5.3,8.8,35.5,3.00,2,95,15.8,90
7,NEIGHBORHOOD SCHOOL,0,33.34,3,32.1,12.2,9.6,9.5,0.75,1,310,7.1,39
8,P.S. 015 ROBERTO CLEMENTE,0,63.28,3,31.9,5.8,8.0,18.1,0.00,2,190,11.0,83
9,P.S. 019 ASHER LEVY,0,50.39,1,50.8,9.0,11.4,30.4,0.00,1,241,15.4,75
10,P.S. 020 ANNA SILVER,0,57.37,0,69.7,9.7,20.0,37.7,2.25,1,476,7.7,56
11,P.S. 034 FRANKLIN D. ROOSEVELT,1,58.96,1,59.8,4.5,10.6,37.9,6.75,1,293,13.7,98
12,P.S. 063 WILLIAM MCKINLEY,0,53.00,4,26.5,7.6,11.3,7.6,0.00,2,1859,4.7,73
13,P.S. 064 ROBERT SIMON,0,60.63,0,79.7,12.1,18.9,46.4,2.25,1,236,11.9,95
14,P.S. 110 FLORENCE NIGHTINGALE,0,42.56,2,41.2,9.4,16.9,13.4,1.50,1,396,7.0,56
15,P.S. 134 HENRIETTA SZOLD,0,54.03,1,53.0,5.8,14.4,31.3,1.50,2,254,14.9,89

In [25]:
def grade(x):
    if x == 0:
        return 1
    if x == 1:
        return 1
    else:
        return 0
    
new_new['Pass/Fail'] = new_new['OVERALL GRADE'].apply(grade)

In [26]:
new_new

,SCHOOL,SCHOOL LEVEL,PEER INDEX,OVERALL GRADE,OVERALL SCORE,ENVIRONMENT CATEGORY SCORE,PERFORMANCE CATEGORY SCORE,PROGRESS CATEGORY SCORE,ADDITIONAL CREDIT,2007-08 QUALITY REVIEW SCORE,Enrollment,Student-Teacher Ratio,Free-Reduced Lunch,Pass/Fail
0,BARD HIGH SCHOOL EARLY COLLEGE,3,3.79,1,57.8,10.9,15.9,31.0,0.00,2,614,4.9,44,1
1,P.S. 140 NATHAN STRAUS,1,62.46,1,64.8,9.0,15.3,36.0,4.50,2,318,9.2,72,1
2,EARTH SCHOOL,0,34.68,0,62.4,11.9,9.8,36.9,3.75,1,344,7.3,48,1
4,EAST SIDE COMMUNITY HIGH SCHOOL,3,2.27,0,68.3,13.0,19.9,33.4,2.00,1,675,6.4,67,1
6,MARTA VALLE SECONDARY SCHOOL,3,2.08,1,52.6,5.3,8.8,35.5,3.00,2,95,15.8,90,1
7,NEIGHBORHOOD SCHOOL,0,33.34,3,32.1,12.2,9.6,9.5,0.75,1,310,7.1,39,0
8,P.S. 015 ROBERTO CLEMENTE,0,63.28,3,31.9,5.8,8.0,18.1,0.00,2,190,11.0,83,0
9,P.S. 019 ASHER LEVY,0,50.39,1,50.8,9.0,11.4,30.4,0.00,1,241,15.4,75,1
10,P.S. 020 ANNA SILVER,0,57.37,0,69.7,9.7,20.0,37.7,2.25,1,476,7.7,56,1
11,P.S. 034 FRANKLIN D. ROOSEVELT,1,58.96,1,59.8,4.5,10.6,37.9,6.75,1,293,13.7,98,1
12,P.S. 063 WILLIAM MCKINLEY,0,53.00,4,26.5,7.6,11.3,7.6,0.00,2,1859,4.7,73,0
13,P.S. 064 ROBERT SIMON,0,60.63,0,79.7,12.1,18.9,46.4,2.25,1,236,11.9,95,1
14,P.S. 110 FLORENCE NIGHTINGALE,0,42.56,2,41.2,9.4,16.9,13.4,1.50,1,396,7.0,56,0
15,P.S. 134 HENRIETTA SZOLD,0,54.03,1,53.0,5.8,14.4,31.3,1.50,2,254,14.9,89,1

In [27]:
new_new.drop(['OVERALL GRADE'], axis=1, inplace=True)

In [28]:
new_new

,SCHOOL,SCHOOL LEVEL,PEER INDEX,OVERALL SCORE,ENVIRONMENT CATEGORY SCORE,PERFORMANCE CATEGORY SCORE,PROGRESS CATEGORY SCORE,ADDITIONAL CREDIT,2007-08 QUALITY REVIEW SCORE,Enrollment,Student-Teacher Ratio,Free-Reduced Lunch,Pass/Fail
0,BARD HIGH SCHOOL EARLY COLLEGE,3,3.79,57.8,10.9,15.9,31.0,0.00,2,614,4.9,44,1
1,P.S. 140 NATHAN STRAUS,1,62.46,64.8,9.0,15.3,36.0,4.50,2,318,9.2,72,1
2,EARTH SCHOOL,0,34.68,62.4,11.9,9.8,36.9,3.75,1,344,7.3,48,1
4,EAST SIDE COMMUNITY HIGH SCHOOL,3,2.27,68.3,13.0,19.9,33.4,2.00,1,675,6.4,67,1
6,MARTA VALLE SECONDARY SCHOOL,3,2.08,52.6,5.3,8.8,35.5,3.00,2,95,15.8,90,1
7,NEIGHBORHOOD SCHOOL,0,33.34,32.1,12.2,9.6,9.5,0.75,1,310,7.1,39,0
8,P.S. 015 ROBERTO CLEMENTE,0,63.28,31.9,5.8,8.0,18.1,0.00,2,190,11.0,83,0
9,P.S. 019 ASHER LEVY,0,50.39,50.8,9.0,11.4,30.4,0.00,1,241,15.4,75,1
10,P.S. 020 ANNA SILVER,0,57.37,69.7,9.7,20.0,37.7,2.25,1,476,7.7,56,1
11,P.S. 034 FRANKLIN D. ROOSEVELT,1,58.96,59.8,4.5,10.6,37.9,6.75,1,293,13.7,98,1
12,P.S. 063 WILLIAM MCKINLEY,0,53.00,26.5,7.6,11.3,7.6,0.00,2,1859,4.7,73,0
13,P.S. 064 ROBERT SIMON,0,60.63,79.7,12.1,18.9,46.4,2.25,1,236,11.9,95,1
14,P.S. 110 FLORENCE NIGHTINGALE,0,42.56,41.2,9.4,16.9,13.4,1.50,1,396,7.0,56,0
15,P.S. 134 HENRIETTA SZOLD,0,54.03,53.0,5.8,14.4,31.3,1.50,2,254,14.9,89,1

In [29]:
new_new.to_csv('2007-2008_Sample_Data.csv')